### ISSUE TITLE
Work around api request limits

### ISSUE THREAD

**Issue by mesqueeb** [Dappos/Dappos#20]
From coinmarketcap
> Please limit requests to no more than 30 per minute.

**Comment by hiroingk** [comment]
I had this problem while using Dappos. I'm going to fix this problem using Firebase functions and Firestore.

**Comment by mesqueeb** [comment]
new api coinmarketcap will have hard cap of 333 reads / day.
to work around this limit, for now:

Get rate from firestore with a [transaction](https://firebase.google.com/docs/firestore/manage-data/transactions):
in the transaction:
1. read data: "rate & last updated-timestamp"
2. if (last updated-timestamp < 1 min) use that rate
3. if not, get new rate from coinmarketcap & write to firestore

**Comment by tmlee** [comment]
you may consider using our public free API at https://www.coingecko.com/api
it should be straightforward to consume and switch

Let me know if you have any questions or concerns

**Comment by mesqueeb** [comment]
@tmlee Thanks a lot for letting me know! I'm going to try to implement this one now.

**Comment by mesqueeb** [comment]
@tmlee For the functionality to offer the user to add custom ERC20 tokens, we'll have them include the coinGecko id of that token for the conversion.

What is the best way for normal users to know this id? We'll have to add some explanation on this.

**Comment by mesqueeb** [comment]
@tmlee I have another question.
I'm trying to implement it, but I received this error:
<img width="831" alt="2018-12-04 18 53 35" src="https://user-images.githubusercontent.com/3253920/49433732-030d0300-f7f6-11e8-9f72-f5220292fde0.png">

I couldn't find any documentation on this.

**Comment by mesqueeb** [comment]
Closed in #38
