### ISSUE TITLE
Add apple touch icon for home screen

### ISSUE THREAD

**Issue by geraldz** [Dappos/Dappos#37]
Save the following image in the server root with the name "apple-touch-icon.png"

Alternately save it in the /statics folder and add the following to the index:

`<link rel="apple-touch-icon" href="/statics/apple-touch-icon.png">`

This will display the Dappos logo when the app is added to the Home Screen 

![apple-touch-icon](https://user-images.githubusercontent.com/15104648/49330247-f66c7e80-f559-11e8-8c61-f4b72d2c9aeb.png)

References:
 1. https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4

2. https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

**Comment by mesqueeb** [comment]
Closed in #38
